pipelines/catalog-builder: drop prefetch-dependencies
it shouldn't be needed since we are building the bundle (maybe bundler
though?)

```
Error: InvalidInput: 1 validation error for user input
packages -> 0
  Input tag 'true' found using 'type' does not match any of the expected tags: 'bundler', 'cargo', 'generic', 'gomod', 'npm', 'pip', 'rpm', 'yarn'
```

Signed-off-by: Brady Pratt <bpratt@redhat.com>